package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/spf13/cobra"

	"github.com/lukashankeln/glint/internal/config"
	"github.com/lukashankeln/glint/internal/discovery"
)

const glintYAMLTemplate = `# glint.yaml — generated by ` + "`glint init`" + `
# Detected: {{ .DetectedLabel }}
version: "v1alpha1"

discovery:
  paths: ["."]
  exclude:
    - "vendor/**"
    - "**/.git/**"
    - "**/.terraform/**"

render:
  helm:
    kubernetes_version: "{{ .KubernetesVersion }}"
    include_crds: true
  subprocess_fallback: false

schema:
  enabled: true
  kubernetes_version: "{{ .KubernetesVersion }}"
  ignore_missing_schemas: true
  skip_kinds:
    - CustomResourceDefinition

rules:
  built_in:
    no_latest_tag:
      enabled: true
      severity: error
    resource_requests:
      enabled: {{ .EnableResourceRequests }}
      severity: warning
    deprecated_apis:
      enabled: true
      severity: error

  # Custom CEL rules — add your own policies here:
  custom: []

  # Load rules from additional files:
  # rule_files:
  #   - "glint-rules/*.yaml"

output:
  format: text
  color: auto
  summary: true

fail_on:
  - error
`

type initTemplateVars struct {
	DetectedLabel         string
	KubernetesVersion     string
	EnableResourceRequests string
}

func newInitCmd() *cobra.Command {
	var force bool
	var framework string

	cmd := &cobra.Command{
		Use:   "init [path]",
		Short: "Scaffold a starter glint.yaml in the target directory",
		Args:  cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			root := "."
			if len(args) > 0 {
				root = args[0]
			}

			outPath := filepath.Join(root, "glint.yaml")
			if _, err := os.Stat(outPath); err == nil && !force {
				return fmt.Errorf("%s already exists — use --force to overwrite", outPath)
			}

			vars := initTemplateVars{
				KubernetesVersion:      config.DefaultKubernetesVersion,
				EnableResourceRequests: "false",
			}

			// Auto-detect framework unless forced.
			detected := framework
			if detected == "" {
				detected = detectDominantFramework(cmd, root)
			}

			switch detected {
			case "argocd":
				vars.DetectedLabel = "ArgoCD framework"
				vars.EnableResourceRequests = "true"
			case "flux":
				vars.DetectedLabel = "Flux framework"
				vars.EnableResourceRequests = "true"
			default:
				vars.DetectedLabel = "plain Kubernetes manifests"
			}

			tmpl, err := template.New("glint.yaml").Parse(glintYAMLTemplate)
			if err != nil {
				return fmt.Errorf("parsing template: %w", err)
			}

			f, err := os.Create(outPath)
			if err != nil {
				return fmt.Errorf("creating %s: %w", outPath, err)
			}
			defer f.Close()

			if err := tmpl.Execute(f, vars); err != nil {
				return fmt.Errorf("rendering template: %w", err)
			}

			fmt.Fprintf(cmd.OutOrStdout(), "Created %s (detected: %s)\n", outPath, vars.DetectedLabel)
			return nil
		},
	}

	cmd.Flags().BoolVar(&force, "force", false, "overwrite existing glint.yaml")
	cmd.Flags().StringVar(&framework, "framework", "", "force framework: argocd|flux|plain (default: auto-detect)")
	return cmd
}

// detectDominantFramework runs a lightweight discovery pass and returns the
// framework seen most frequently across discovered apps.
func detectDominantFramework(cmd *cobra.Command, root string) string {
	cfg, err := config.Load("")
	if err != nil {
		return "plain"
	}
	cfg.Discovery.Paths = []string{root}

	apps, err := discovery.Discover(cmd.Context(), []string{root}, cfg)
	if err != nil || len(apps) == 0 {
		return "plain"
	}

	counts := map[discovery.Framework]int{}
	for _, app := range apps {
		counts[app.Framework]++
	}

	best := discovery.FrameworkPlain
	max := 0
	for fw, n := range counts {
		if n > max {
			max = n
			best = fw
		}
	}
	return string(best)
}
