name: Docker

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: kube-the-home/github-actions/.github/workflows/docker-build.yaml@7d8043b1d454e713b465c324c99d929a4a625a98 # v1.4.12
    with:
      image: ghcr.io/lukashankeln/glint
      tag: ${{ github.ref_name }}
    secrets:
      registry_password: ${{ secrets.GITHUB_TOKEN }}
