name: Docker

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: kube-the-home/github-actions/.github/workflows/docker-build.yaml@962260b6048afd17325015c372eeb835a04b25b2 # v1.4.2
    with:
      image: ghcr.io/lukashankeln/glint
      tag: ${{ github.ref_name }}
    secrets:
      registry_password: ${{ secrets.GITHUB_TOKEN }}
