name: Release

on:
  push:
    branches: [main]

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    uses: kube-the-home/github-actions/.github/workflows/release-please.yaml@cb85be74aea09666f090472a4dcb92dad3ed3680 # v1.4.0
    with:
      config_file: release-please-config.json
      manifest_file: .release-please-manifest.json
      release_type: go
    secrets:
      APP_ID: ${{ secrets.RELEASE_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.RELEASE_APP_PEM }}
