name: Release

on:
  push:
    branches: [main]

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    uses: kube-the-home/github-actions/.github/workflows/release-please.yaml@a742a2eda2b622e6902ee5e97db2fcd1d6c432a9 # v1.4.7
    with:
      config_file: release-please-config.json
      manifest_file: .release-please-manifest.json
    secrets:
      APP_ID: ${{ secrets.RELEASE_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.RELEASE_APP_PEM }}
