name: Release

on:
  push:
    branches: [main]

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    uses: kube-the-home/github-actions/.github/workflows/release-please.yaml@e698429ae3d6096c14d7eb6d2ffef1da8c26cdea # v1.4.1
    with:
      config_file: release-please-config.json
      manifest_file: .release-please-manifest.json
    secrets:
      APP_ID: ${{ secrets.RELEASE_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.RELEASE_APP_PEM }}
